### ISSUE TITLE
Linting doesn't automatically trigger for files that are already opened

### ISSUE THREAD

**Issue by lubyrex** [coc-extensions/coc-omnisharp#20] opened 2020-05-06 07:52 UTC
Right now linting doesn't seem to work for cs files that I open too quickly:
![image](https://user-images.githubusercontent.com/16534505/81149453-d2b03200-8fb0-11ea-882d-7f8ad1e8d3a0.png)
but after reloading the file with `:e`, the linting comes back:
![image](https://user-images.githubusercontent.com/16534505/81149569-07bc8480-8fb1-11ea-8ec6-3be7c229b8d9.png)
Linting works fine for files that I open after a period of time.

Any idea how I can solve this problem?
I'm using neovim on windows 10 btw.
There aren't any Errors in the language server output.

**Comment by ichirou2910** [comment] 2020-06-18 16:12
Same problem with Neovim 0.4.3 on Arch Linux, must :e to make the linting work :cry:

**Comment by yatli** [comment] 2020-11-20 07:40
Dupe of https://github.com/coc-extensions/coc-omnisharp/issues/33, fixed.

**Closed by yatli** 2020-11-20 07:40 UTC
