### ISSUE TITLE
FAILURE: "Could not locate '.../.msbuild/Current/Bin/Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll'"

### ISSUE THREAD

**Issue by en3on** [coc-extensions/coc-omnisharp#13] opened 2019-11-12 08:51 UTC
I have done a clean install of nvim + omnisharp in a WSL container (Debian)

omnisharp is throwing a couple of errors because it can't find certain DLLs in the .msbuild folder.

[Log File](https://pastebin.com/0AW49kaY)

**Comment by kori4r2** [comment] 2020-03-17 19:52
Any updates/workarounds for this? Still getting the exact same error here

**Comment by yatli** [comment] 2020-03-18 05:56
Is the file actually there?

There we a few reports now and then, resolved by a re-installation.

**Comment by kori4r2** [comment] 2020-03-18 18:52
No it isn't. I actually have omnisharp on vs code working properly without the file and I have already reinstalled both mono and coc-omnisharp. The file isn't there, the problem is it shouldn't be trying to find the file anyway, I checked a lot of previous omnisharp versions on the github release history, none of them have those *.resources.dll files the plugin is trying to find.

**Comment by yatli** [comment] 2020-03-19 06:12
Ha. I updated my installation in WSL and got a repro.

**Comment by yatli** [comment] 2020-03-19 10:31
Tracking: https://github.com/OmniSharp/omnisharp-roslyn/issues/1742

**Comment by svermeulen** [comment] 2020-04-15 19:03
Any workaround to this?

**Comment by mikejzx** [comment] 2020-04-16 20:43
Getting this same issue too, and [#9 ](https://github.com/coc-extensions/coc-omnisharp/issues/9#issue-497944873)

**Comment by toyboot4e** [comment] 2020-04-21 11:52
Temporaly solution is.. using [omnisharp-vim](https://github.com/OmniSharp/omnisharp-vim) with ALE or Syntastic ;)

**Comment by yatli** [comment] 2020-11-20 07:28
Fixed!

**Closed by yatli** 2020-11-20 07:28 UTC
Labels: Upstream
